
permalink:           pretty
# Setup
title:               'Computer vision and Image Processing'
homepage_title:      Home
url:                 https://iknyazeva.github.io/CV2020/
baseurl:             '/CV2020'

src:                 "."
default_theme:       "rust"

# For Maths
markdown:            kramdown
 
prologues:
  - path: about.md
  - path: tools.md
chapters:
 - path: week01/01.md
   sections:
     - path: week01/01-1.md
     - path: week01/01-2.md
     - path: week01/01-notes.md

