theme: jekyll-theme-minimal
permalink:           pretty
# Setup
title:               'Deep Learning'
url:                 https://iknyazeva.github.io/CV2020/
#baseurl:             '/CV2020'
homepage_title:      Home


# For Maths
markdown:            kramdown

plugins:
  - jekyll-katex
